"""Add new features

Revision ID: c6328a421238
Revises: 52a54f9317ff
Create Date: 2025-07-16 23:25:33.074345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6328a421238'
down_revision = '52a54f9317ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertiser.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advertiser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_scope', sa.Enum('CITY', 'CITY_REGION', 'CITY_REGION_OTHER_STATES', name='adscope'), nullable=False))
        batch_op.add_column(sa.Column('has_had_trial', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertiser', schema=None) as batch_op:
        batch_op.drop_column('has_had_trial')
        batch_op.drop_column('ad_scope')

    op.drop_table('report')
    # ### end Alembic commands ###
